### PR TITLE
used variables added icons

### PR DESCRIPTION
**Pull request by MahimaSusan**
@nishintn 
   Used variable, changed buttons into icons and changed the allignment

The local link is    http://10.9.12.128:8081/views/#/activity_logger/todolog

### CODE REVIEW

**Comment by mad-nishin** [comment]
@MahimaSusan 
The UI doesnt look good. Need to align better.

**Comment by MahimaSusan** [comment]
@nishintn 
The local link for changed UI is http://10.9.12.128:8080/views/#/activity_logger/todolog

**Comment by MahimaSusan** [comment]
@nishintn 
added x-icon
The local link for changed UI is http://10.9.12.128:8080/views/#/activity_logger/todolog

**Comment by MahimaSusan** [comment]
@nishintn 
UI changed 
The local link for changed UI is 
http://10.9.12.128:8080/Desktop/ToDo-App/views/#/activity_logger/todolog

**Pull request merged**
